[project]
name = "PyTSML"
version = "1.0.0"
authors = [
  { name="Adrian Hałys", email="author@example.com" },
]
description = "Placeholder"
readme = "README.md"
keywords = ["Time Series", "Classification", "Machine Learning", "LDMLT", "DDE", "DE", "Delay Embedding", "DTW"]
requires-python = ">=3.11"
dependencies = [
"scipy>=1.14.1",
"fastdtw>=0.3.4"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/Bl0tniaQus/PyTSML"
Issues = "https://github.com/Bl0tniaQus/PyTSML/issues"
[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"
